### ISSUE TITLE
Template to remember number of items

### ISSUE THREAD

**Issue by rbpaiett** [niketa-wow/farming-bar#12]
When I save a bar to a custom template, it doesn't remember the number of items for each slot.

It would be helpful to have the option to remember the number of items in each slot if possible.

The alternative is to go back and do all the research for finding out how many of each item you need.  This is helpful for a specific shopping list instead of general.

**Comment by rbpaiett** [comment]
The other reason why I would like it is if you have a shopping list that includes for example 10 Heavy Grinding Stones, I'd like to make a separate shopping list for the Heavy Stones required to make said 10 Heavy Grinding Stones.

Btw, I love the direction to where this addon is heading, it's perfect for my needs!

**Comment by niketa-wow** [comment]
Related to https://github.com/niketa-wow/farming-bar/issues/10

Pardon the formatting. Phone doesn't want to cooperate.

**Comment by niketa-wow** [comment]
I like the idea of saving some settings in the template myself, but not sure how a lot of people feel about this. The current functionality is basically carried over from how Farmit did it and I'm not sure if it's just one of the things he never got around to changing or if most people preferred it that way. 

So I'm gonna have to think on it a little bit and decide the best way to approach it.

Here are some ideas:

I could do maybe a setting to toggle on or off on how it should be saved. Would need to figure out if that should be automatic per profile, per global, or maybe just per each new template.

If I did it as a setting, I'd need to figure out if most everyone prefers that and then just make it the default or if people prefer the option. 

I could also make it a completely different type of template but that seems like it'd be more annoying on my end.

Of course this would be in regard to saving both the order and the objectives. I think I would consider those the same request here: you want specific farming information saved with the template.

**Comment by rbpaiett** [comment]
For me, a toggle option is just fine.

**Comment by niketa-wow** [comment]
Implemented in v2.1
