### ISSUE TITLE
Options tooltip for item already in bar slot [REQUEST]

### ISSUE THREAD

**Issue by rbpaiett** [niketa-wow/farming-bar#2]
When an item is already in a slot, at mouseover the tooltip for the item appears with slot options appearing briefly at the bottom (shown circled in the screenshot).  Is there a way to make it so that the options can been seen again at the bottom of the tooltip by pressing something like the Alt key?  The options disappear too quickly for me to read and I don't always remember what the options are.  Sometimes I'll put in the wrong item number or I need to change the target amount.  Hope this description is clear enough. 

![FarmingBar Tooltip](https://user-images.githubusercontent.com/1621701/74110778-378bf580-4b44-11ea-907b-2af580df7b84.jpg)

**Comment by niketa-wow** [comment]
The options should always appear any time you mouseover an item on a bar. So if there is any other item on your bar, you can mouseover it to see the options. If you have nothing on your bars, you can right click the anchor to open the help menu and it should tell you have to put items on there too. The anchor tooltip also reminds you how to open the help menu.

In the update I'm working on, I have tooltips enabled for empty bars too to show important controls, which is what I think you're looking for. That change won't be released until the next major rewrite is released.

![WoWScrnShot_020920_160244](https://user-images.githubusercontent.com/58258335/74110935-3c59a500-4b56-11ea-98c4-150859cd2273.jpg)

**Comment by rbpaiett** [comment]
Oh it does appear, but then that part of the tooltip disappears too fast before I have a chance to read  and understand it all, at least it does with my setup.

**Comment by niketa-wow** [comment]
So, is that when you hover over an item on a button and don't move the cursor? Or are you hovering over an item in your bags?

What other addons are you using that affect tooltips?

**Comment by rbpaiett** [comment]
This is happening when I hover over an item on a button and yes, I don't move it.  

The Auctioneer addon also affects a tooltip by showing information about reselling, disenchanting, etc.  It shows additional information when the mouse hovers over an item and I believe the shift button is pressed.  

The addon UsedInRecipe also makes information about your other characters you have appear when you press the shift key while hovering over an item, even while hovering over a used (populated)  button in your addon.

**Comment by niketa-wow** [comment]
I'm sorry, I have been busy lately. Are you still having issues with your tooltips?

**Comment by rbpaiett** [comment]
It would be nice if the options remained visible a bit longer but over time I've gotten used to it :)

**Comment by niketa-wow** [comment]
I've not been able to replicate the issue you're having. Without more information as to what's causing it to disappear, I'll have to close this ticket. I tried downloading the two addons you mentioned as well to see if it was an interaction with those, but I still can't find the issue. The tips stay displayed on the tooltip the entire time I have hovered over them.
