### ISSUE TITLE
Click item on list for bank withdrawal [REQUEST]

### ISSUE THREAD

**Issue by rbpaiett** [niketa-wow/farming-bar#3]
One thing that would be nice is if you have a goal in place (number of items desired), you could click on them (shift-click, or other) and the number of items remaining would be taken from the bank and put into your inventory.

For instance:  You have a goal for 60 light leather and in your bags you have 40.  At the same time you have 30 in the bank.  When you open the bank, you would click on the light leather listed in the app slot and the needed 20 light leather would then be transferred to your bags.

This is just a convenience feature that would be very nice :)

This would be very similar to the shopping list feature in the Skillet addon but one item at a time which is no big deal (or perhaps you could do for eg:  Alt-Click for one item withdrawal and perhaps Ctrl-Click for all items with a goal.

Programming wise, the one at a time click may be easier to program.

Hope I was clear in my description.

**Comment by niketa-wow** [comment]
This is something I can look into implementing.

**Comment by niketa-wow** [comment]
Implemented for the upcoming update.

**Comment by rbpaiett** [comment]
Awesome, tyvm!

**Comment by rbpaiett** [comment]
Any word on when this upcoming update would take place?  I haven't seen it since your last remark ... unless I've lost my mind of course.

**Comment by niketa-wow** [comment]
This repository just holds the source code that I write before it gets packaged. You have to download a version that's been packaged for release as it embeds the libraries and even comments out certain lines for retail vs classic. 

After my last comment it took a little bit to apply some finishing touches before release but it was officially released yesterday as a beta. You can download it via Curseforge or WoW Interface. If you use the twitch client you can right-click and set it to install release type and set it to beta and it'll offer an update. On the curseforge site, go to files and download FarmingBar-v2.0.2-beta2-classic. Or in wowinterface should be able to just choose the classic version as it doesn't support betas so it shows as a release.

**Comment by niketa-wow** [comment]
Also want to add that I'm a little worried that since you didn't have the correct file that your data might be erased. If you have access to previous versions and can back it up in case, I would. 

But if you didn't have any libraries, I think you should be ok because I think it would have given you an error before you even got to the point where your settings would be compromised.
