### ISSUE TITLE
Sound audio missing from sound selection [BUG] 

### ISSUE THREAD

**Issue by rbpaiett** [niketa-wow/farming-bar#5]
**Describe the bug**
In the settings, when the sound 'auction house' is selected, there is no audio for it.

**Client**
113.4 (this is on the beta version of this addon)

**To Reproduce**
1. Go to 'settings'
2. Click on 'auction house'
3. Scroll down to 'N/A'
4. No audio sound when you click the speaker

**Expected behavior**
I expect an auction open sound, I get nothing

**Screenshots**
can be provided if needed.

**Additional context**
n/a

**Comment by niketa-wow** [comment]
Are you able to hear the sounds for other options and just not this one or none at all?

**Comment by rbpaiett** [comment]
I answered this in my commentary to the other bug report.
