### ISSUE TITLE
No audio cue after shopping list complete [BUG] 

### ISSUE THREAD

**Issue by rbpaiett** [niketa-wow/farming-bar#7]
**Describe the bug**
When the shopping list was complete, there was no 'quest complete' sound or anything

**Client**
113.4 (Beta Addon version)

**To Reproduce**
1. Set up shopping list in 'ctrl-right-click' menu
2. Gather all items in shopping list

**Expected behavior**
Expected 'quest complete' audio cue after all items gathered.

**Screenshots**
Can be provided if requested

**Additional context**
Since this is beta, you may not have completed this section of the addon.  Not sure whether to put it under request or bug.

**Comment by niketa-wow** [comment]
1. Which sound do you have selected for the objective complete?
2. Does completing an objective for an item or mixed items work? Or do none?

**Comment by rbpaiett** [comment]
For the objective complete I have Quest Completed selected.
Ok, here are the scenarios:
1.  When clicking on the bell in the sound settings list, the ones that make no sound are:
  
        Auction House
        Loot Coin
        Quest Activate
        Quest Complete
        Quest Fail

2.  After selecting the sounds I desire:
  
        A.  With 'Farming Progress', no sound happens at all, whether I use the banking shortcuts or manually clicking them from the bank to the inventory (or buy all needed items from a vendor).
  
        B.  With 'Objective Cleared' (or Sub-Objective Completed I like to say), no sound happens at all, whether I use the banking shortcuts or manually take them from the bank to the inventory (or buy all needed items from a vendor).
  
        C.  With 'Objective Complete' (or shopping list is complete) and I use the banking shortcuts, no sound happens at all.  However, when I manually take them from the bank to the inventory (or buy all needed items from a vendor, I get the sound.

3.  In all cases, all visual cues happen properly.

**Comment by niketa-wow** [comment]
I will have to look into the sounds when I get home to see what's going on, but one thing to note is I disabled all alerts when moving items with the shortcut so it wouldn't be spammy. If this is something you don't like, I can either change it or make it an option.

**Comment by niketa-wow** [comment]
I re-enabled alerts for chat and sound while the moving frame is up, but changed screen alerts to show as the status message of the frame. It goes by pretty fast, but otherwise it would just overlap and be even more of a mess.

So far I have the sounds working on my end. The issue was that retail (which is where I code primarily) allows file IDs for the sound paths, whereas I had to use the actual path for classic.

I just need to work on fixing the way shopping lists count to make sure the correct progress sounds work. After that, this ticket will be done.

**Comment by niketa-wow** [comment]
Please download FarmingBar-v2.0.4-beta-classic to make sure the issues in this ticket have been resolved. If they haven't, reopen the ticket. Thanks!

**Comment by rbpaiett** [comment]
Sounds all work nicely in all scenarios, thanks again!
