### ISSUE TITLE
Count text y-offset not staying after reload or logout[BUG] 

### ISSUE THREAD

**Issue by Tednik** [niketa-wow/farming-bar#9]
**Describe the bug**
Bar Count text y-offset is not maintaining its position on reload or logout

**Client**
retail

**To Reproduce**
1. Go to bar settings 
3. Scroll down to count text y-offset change value 
4.reload ui or log out then back in count text does not stay where it was set to but value is still what it should be

**Expected behavior**

**Screenshots**
https://i.imgur.com/LBcpBXu.jpg  count text set before reload ui bars are on the left side

https://i.imgur.com/qONCp9X.jpg  count text after reload ui 

**Additional context**

**Comment by niketa-wow** [comment]
I'm not able to reproduce the issue on my end, so you'll have to bear with me. This might be a little hard to troubleshoot.

I notice that in both the before and after, the positions are the same, so I don't think it's a database issue. It's probably something to do with drawing the buttons.

1. If you reload again, does the incorrect position persist?
2. If you change the y-offset, then change it back, does it adjust correctly? And if so, upon reloading does it then revert to the messed up setting?
3. Are you experiencing any lua errors?
4. Are you using Masque? If so, what skin are you using on Farming Bar?

**Comment by Tednik** [comment]
1. yes it does persist
2. yes if i change it ot click in the number box and hit enter it adjusts correctly then if i log out or reload yes it reverts to the count text being back on top of the bars
3. no lua errors
4. yes im using masque,  Masque_CB - Elv

**Comment by niketa-wow** [comment]
Sorry it took so long to get back to you. I've had a busy weekend.

I've fixed the issue and you should be seeing an update in the next half hour or so. Thanks for bringing this to my attention!

**Comment by Tednik** [comment]
No problem thank you for fixing it
